### ISSUE TITLE
interpolateHcl and achromatic colors

### ISSUE THREAD

**Issue by danburzo** [d3/d3-interpolate#50]
Interpolating `red` and `white` in Lab and HCL:

<img width="303" alt="screen shot 2018-04-04 at 15 29 10" src="https://user-images.githubusercontent.com/205375/38307637-fefcad72-381c-11e8-9a99-9de072bc706e.png">

Due to the particular HCL hue of achromatic colors (~ 158.2° in the current implementation of d3-color), when interpolating a chromatic and achromatic color, the non-zero Chroma of the interpolated color will pick up various hues.

In comparison, chroma.js will not interpolate the hue in this case, with a more predictable (and analogous to Lab) outcome:

<img width="324" alt="screen shot 2018-04-04 at 15 35 12" src="https://user-images.githubusercontent.com/205375/38307851-ce513dc2-381d-11e8-8baf-e8a6c9c13b5a.png">

Should _interpolateHcl_ behave the same?

**Comment by mbostock** [comment]
The big here (if there is one, and I think there is) is that the hue for white (or another achromatic color) is a number rather than NaN. If the hue is NaN then the interpolator will do the right thing.

Previously I thought that the non-NaN (NNaN) hue for white was an artifact of the D65 referent but it seems I was mistaken. We should fix this as part of your work to make d3.lab and d3.lch consistent with other implementations.

(Also would be great to implement chroma clamping…)

**Comment by mbostock** [comment]
Fixed in d3-color 1.0.4.

https://beta.observablehq.com/@mbostock/achromatic-interpolation-test
